name: Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore PaymentService/PaymentService.sln

      - name: Build
        run: dotnet build PaymentService/PaymentService.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test PaymentService/PaymentService.sln --no-build --configuration Release --verbosity normal
